package constants

const (
	DEFAULT_REDIS_HOST = "localhost"
	DEFAULT_REDIS_PORT = 6379
	DEFAULT_DATABASE   = 0

	REDIS_GET = "GET"
	REDIS_SET = "SET"

	REDIS_STATUS_ERROR   = "ERROR"
	REDIS_STATUS_SUCCESS = "OK"
)
